language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g gulp-cli
  - npm install -g bower
install:
  - npm install
  - bower install
script:
  - gulp test
  - gulp build
sudo: false
after_success:
  - gulp coveralls
