language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp-cli
- npm install -g bower
- npm install npm-prepublish
install:
- npm install
- bower install
script:
- gulp test
- gulp build
sudo: false
before_deploy:
- npm-prepublish --verbose
after_success:
- gulp coveralls
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  # NPM_EMAIL
  - secure: "F9AeS8lL76duXsq+KZJ2cxe6ryOpJp/ruF6KcvB5tlQ86d2IN0+szANx2LdEfKgMnVlj616xCXyHNyORfoPeulXUmRubbdgWshihC07D19FMfc0j06Yv0r3hCfDuo0UaM2l38FzZWUU/q3KaiPAGlKMg1Vxac2g1ZjYg5/d2qkM="
  # NPM_API_KEY
  - secure: "Ascjy6LEXaDFEGg41A5FMYZq6mKQqpKW5WMX3SVajSj6fPXDQaJsF39n9/WhBV2EWkLPCW3KeOIPOqibGpR1ks6ep5rA4B2HvrlNav/KGSuJyMYvM/iRyszo5M8jsXQIp+prj3C9u4m7zi9Sq3uR1VteMOAGY77O6aRqCH2eFWw="