language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
script:
  - grunt test
  - grunt build
sudo: false
after_success:
  - grunt coveralls
